[build]
  base    = "site"
  publish = "public"        
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
