baseURL = "/"
languageCode = "ja"
title = "Walkerpedia"
theme = "hugo-book" 

[taxonomies]
  tag        = "tags"
  category   = "categories"
  character  = "characters"
  place      = "places"
  item       = "items"
  concept    = "concepts"
  org        = "orgs"
  source     = "sources"
  writing    = "writings"